/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var namespaces_address_pb = require('../namespaces/address_pb.js');
goog.exportSymbol('proto.customerdata.Customer', null, global);
goog.exportSymbol('proto.customerdata.CustomerType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.customerdata.Customer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.customerdata.Customer.repeatedFields_, null);
};
goog.inherits(proto.customerdata.Customer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.customerdata.Customer.displayName = 'proto.customerdata.Customer';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.customerdata.Customer.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.customerdata.Customer.prototype.toObject = function(opt_includeInstance) {
  return proto.customerdata.Customer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.customerdata.Customer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.customerdata.Customer.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    addressesList: jspb.Message.toObjectList(msg.getAddressesList(),
    namespaces_address_pb.Address.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.customerdata.Customer}
 */
proto.customerdata.Customer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.customerdata.Customer;
  return proto.customerdata.Customer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.customerdata.Customer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.customerdata.Customer}
 */
proto.customerdata.Customer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.customerdata.CustomerType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new namespaces_address_pb.Address;
      reader.readMessage(value,namespaces_address_pb.Address.deserializeBinaryFromReader);
      msg.addAddresses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.customerdata.Customer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.customerdata.Customer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.customerdata.Customer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.customerdata.Customer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      namespaces_address_pb.Address.serializeBinaryToWriter
    );
  }
};


/**
 * optional CustomerType type = 1;
 * @return {!proto.customerdata.CustomerType}
 */
proto.customerdata.Customer.prototype.getType = function() {
  return /** @type {!proto.customerdata.CustomerType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.customerdata.CustomerType} value */
proto.customerdata.Customer.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated Address addresses = 2;
 * @return {!Array.<!proto.customerdata.Address>}
 */
proto.customerdata.Customer.prototype.getAddressesList = function() {
  return /** @type{!Array.<!proto.customerdata.Address>} */ (
    jspb.Message.getRepeatedWrapperField(this, namespaces_address_pb.Address, 2));
};


/** @param {!Array.<!proto.customerdata.Address>} value */
proto.customerdata.Customer.prototype.setAddressesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.customerdata.Address=} opt_value
 * @param {number=} opt_index
 * @return {!proto.customerdata.Address}
 */
proto.customerdata.Customer.prototype.addAddresses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.customerdata.Address, opt_index);
};


proto.customerdata.Customer.prototype.clearAddressesList = function() {
  this.setAddressesList([]);
};


/**
 * @enum {number}
 */
proto.customerdata.CustomerType = {
  REGULAR: 0,
  MEMBER: 1,
  SPONSOR: 2
};

goog.object.extend(exports, proto.customerdata);
